from core.model_manager import ModelManager
from core.research_orchestrator import MedicalResearchOrchestrator
from typing import Callable, Optional, Dict, Any

class DoctorAI:
    """AI Medical Assistant providing advice and orchestrating deep research."""
    
    def __init__(self):
        self.model_manager = ModelManager()
        self.research_orchestrator = MedicalResearchOrchestrator(self.model_manager)
        self.context_simple_query = (
            "You are an advanced AI medical assistant. Provide direct, clear, and actionable medical "
            "information and advice based on established medical science and clinical guidelines. "
            "Focus on delivering practical insights and evidence-based recommendations. "
            "Do not use tools for this request, answer directly based on your knowledge."
        )

    def set_progress_callback(self, callback_function: Optional[Callable[[str, str], None]] = None) -> None:
        """Sets the progress callback for the research orchestrator."""
        if callback_function:
            self.research_orchestrator.set_progress_callback(callback_function)

    def get_current_research_state(self) -> Dict[str, Any]:
        """Returns the current state of the research orchestrator for UI updates."""
        return self.research_orchestrator.current_research_state

    def get_medical_advice(self, symptoms: str, deep_research: bool = False) -> str:
        """Get medical advice based on symptoms, optionally performing deep research."""
        if not symptoms:
            return "Please provide symptoms to get medical advice."

        if deep_research:
            self._report_progress("Deep research initiated for symptoms.")
            return self.research_orchestrator.run_research_workflow(f"Medical advice for symptoms: {symptoms}")
        else:
            self._report_progress("Simple query for medical advice.")
            prompt = f"""Based on the following symptoms, provide general medical advice and recommendations:
            Symptoms: {symptoms}
            
            Please include in your response, if applicable:
            1. Possible general (non-diagnostic) causes related to these symptoms.
            2. General self-care or lifestyle recommendations that might be relevant.
            3. Clear indicators or red flags for when to seek immediate medical attention from a doctor or emergency services.
            
            Keep your response concise and focused on these three areas. Do not provide a diagnosis. Conclude by advising to consult a healthcare professional for diagnosis and treatment."""
            
            response_message, model_used = self.model_manager.create_completion(
                messages=[
                    {"role": "system", "content": self.context_simple_query},
                    {"role": "user", "content": prompt}
                ],
                reasoning_level="high",
                temperature=0.5,
                max_tokens=1000
            )
            self._report_progress(f"Standard medical advice generated by {model_used}.")
            return response_message.content if response_message and response_message.content else "Could not retrieve advice at this time."

    def get_medication_info(self, medication: str, deep_research: bool = False) -> str:
        """Get information about a medication, optionally performing deep research."""
        if not medication:
            return "Please provide a medication name to get information."

        if deep_research:
            self._report_progress("Deep research initiated for medication.")
            return self.research_orchestrator.run_research_workflow(f"Detailed information for medication: {medication}")
        else:
            self._report_progress("Simple query for medication information.")
            prompt = f"""Provide comprehensive information about the following medication: '{medication}'.
            
            Please include in your response:
            1. Classification and mechanism of action.
            2. Common uses and indications.
            3. Typical dosing guidelines (if generally available, state it's general).
            4. Common side effects.
            5. Important warnings, precautions, and contraindications.
            6. Potential major drug interactions to be aware of.
            
            Structure the information clearly. Conclude by advising to consult a healthcare professional or pharmacist for specific guidance."""
            
            response_message, model_used = self.model_manager.create_completion(
                messages=[
                    {"role": "system", "content": self.context_simple_query},
                    {"role": "user", "content": prompt}
                ],
                reasoning_level="medium",
                temperature=0.4,
                max_tokens=1200
            )
            self._report_progress(f"Standard medication info generated by {model_used}.")
            return response_message.content if response_message and response_message.content else "Could not retrieve medication information at this time."

    def get_lifestyle_advice(self, condition: str, deep_research: bool = False) -> str:
        """Get lifestyle advice for a condition, optionally performing deep research."""
        if not condition:
            return "Please provide a health condition to get lifestyle advice."

        if deep_research:
            self._report_progress("Deep research initiated for lifestyle advice.")
            return self.research_orchestrator.run_research_workflow(f"Lifestyle recommendations for managing: {condition}")
        else:
            self._report_progress("Simple query for lifestyle advice.")
            prompt = f"""Provide lifestyle recommendations for managing or improving the health condition: '{condition}'.
            
            Please include in your response, if applicable:
            1. Dietary recommendations (general guidelines, not specific meal plans).
            2. Exercise and physical activity guidelines.
            3. Stress management techniques.
            4. Sleep hygiene recommendations.
            5. Habits to consider avoiding or adopting.
            6. When it is important to consult healthcare professionals regarding these lifestyle changes.
            
            Focus on evidence-based, general advice. Conclude by emphasizing consultation with healthcare providers for personalized plans."""
            
            response_message, model_used = self.model_manager.create_completion(
                messages=[
                    {"role": "system", "content": self.context_simple_query},
                    {"role": "user", "content": prompt}
                ],
                reasoning_level="medium",
                temperature=0.5,
                max_tokens=1200
            )
            self._report_progress(f"Standard lifestyle advice generated by {model_used}.")
            return response_message.content if response_message and response_message.content else "Could not retrieve lifestyle advice at this time."

    def _report_progress(self, message: str, status: str = "running") -> None:
        """Helper to print progress, could be expanded for logging."""
        print(f"DoctorAI: {message} [Status: {status}]")
        # If a UI callback is set in orchestrator, it will handle UI updates.
        # This is mostly for console logging from DoctorAI itself. 